apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/part-of: supportplane
spec:
  selector:
    app.kubernetes.io/name: openbao
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
  type: ClusterIP
