apiVersion: v1
kind: Service
metadata:
  name: supportplane-web
  namespace: supportplane-app
  labels:
    app.kubernetes.io/name: supportplane-web
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: supportplane-web
  ports:
    - port: 3200
      targetPort: 3200
      name: http
