apiVersion: v1
kind: Service
metadata:
  name: glpi
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: glpi
    app.kubernetes.io/part-of: supportplane
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app.kubernetes.io/name: glpi
