apiVersion: v1
kind: Service
metadata:
  name: glpi-mariadb
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: glpi
    app.kubernetes.io/part-of: supportplane
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      name: mysql
  selector:
    app.kubernetes.io/name: glpi
