apiVersion: v1
kind: ConfigMap
metadata:
  name: glpi-config
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: glpi
    app.kubernetes.io/part-of: supportplane
data:
  GLPI_LANG: 'en_GB'
  GLPI_AUTOINSTALL: 'no'
