apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: supportplane-data
  labels:
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
    supportplane.io/non-production: "true"
    supportplane.io/secret-type: local-dev-placeholder
type: Opaque
stringData:
  password: supportplane_dev
  user: supportplane
  database: supportplane
