apiVersion: v1
kind: Service
metadata:
  name: zammad
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: zammad
    app.kubernetes.io/part-of: supportplane
spec:
  selector:
    app.kubernetes.io/name: zammad
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
