apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: supportplane-observability
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: supportplane
spec:
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: 9095
      protocol: TCP
  type: ClusterIP
