apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-jetstream-data
  namespace: supportplane-integrations
  labels:
    app.kubernetes.io/name: nats
    app.kubernetes.io/part-of: supportplane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: standard
