apiVersion: v1
kind: Namespace
metadata:
  name: supportplane-app
  labels:
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
---
apiVersion: v1
kind: Namespace
metadata:
  name: supportplane-data
  labels:
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
---
apiVersion: v1
kind: Namespace
metadata:
  name: supportplane-integrations
  labels:
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
---
apiVersion: v1
kind: Namespace
metadata:
  name: supportplane-observability
  labels:
    app.kubernetes.io/part-of: supportplane
    supportplane.io/sandbox: local-podman
